### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Fuzuto** [TeamBixby/Gun#3] opened 2021-01-08 16:58 UTC
**Error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/Gun-master/src/TeamBixby/Gun/GunPlugin
Line:  34**

**Comment by Furryjaki1992** [comment] 2021-01-08 17:00
**Error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/Gun-master/src/TeamBixby/Gun/GunPlugin
Line: 34**

**Comment by Adam1609** [comment] 2021-01-08 17:05
Please update binary to 7.4, dupe of #1

**Closed as completed** 2021-01-09 01:48 UTC
Labels: invalid
